#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# api_authentication:
#   path: /login_check

api_login_check:
  path: /api/login_check
  controller: App\Controller\AuthController::api_login
  methods: POST

gesdinet_jwt_refresh_token:
  path:       /token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh

confirm_account:
  path: /account/confirm/{token}/{username}

